# Generated by Django 4.2.1 on 2023-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="description",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="disinfection_instructions",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="image",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="scientific_name",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="watering_instructions",
        ),
        migrations.AddField(
            model_name="plant",
            name="common_names",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="edible_parts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="gbif_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="name_authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="propagation_methods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="synonyms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="taxonomy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="wiki_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="wiki_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
