# Generated by Django 4.2.1 on 2023-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_plant_details_delete_plants"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_details",
            name="real_image",
            field=models.ImageField(blank=True, null=True, upload_to="real_images/"),
        ),
    ]
